config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '',
                     path_names: { sign_in: 'entrar',
                                   sign_out: 'sair',
                                   sign_up: 'cadastro' }

  root 'projects#index'

  resources :clients

  resources :contacts

  resources :tasks

  resources :timesheets

  resources :expenses
  
  resources :teams

  resources :reports

  resources :projects do
    post 'archive',   to: 'projects#archive_project',   as: :archive
    post 'unarchive', to: 'projects#unarchive_project', as: :unarchive
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
class Client < ApplicationRecord
  CURRENCY_TYPE = ['R$ BRL', '$ USD', '€ EUR'].freeze

  has_many :contacts, dependent: :destroy
  has_many :projects, dependent: :destroy

  belongs_to :user

  validates :name, presence: true
  validates :currency_type, presence: true
end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :client
  belongs_to :user

  validates :first_name, presence: true
  validates :email, presence: true
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :client
  belongs_to :user
  has_many :timesheets, dependent: :destroy

  validates :name, presence: true
  validates :total_hours, presence: true

  scope :archived,   -> { where(archived: true) }
  scope :unarchived, -> { where(archived: false) }
end

app/models/task.rb
class Task < ApplicationRecord
  has_many :timesheets
  belongs_to :user
  validates :name, presence: true
  validates :billable, presence: true

  scope :get_billable, -> { where(billable: true) }
end

app/models/timesheet.rb
class Timesheet < ApplicationRecord
  belongs_to :project
  belongs_to :task
  belongs_to :user

  validates :description, presence: true
  validates :start_date, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable,
         :trackable, :validatable

  validates :first_name, presence: true
  validates :last_name,  presence: true
  validates :email,      presence: true, format: /\w+@\w+\.{1}[a-zA-Z]{2,}/

  has_many :projects,   dependent: :destroy
  has_many :clients,    dependent: :destroy
  has_many :contacts,   dependent: :destroy
  has_many :tasks,      dependent: :destroy
  has_many :timesheets, dependent: :destroy
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :authenticate_user!

  before_action :set_client, only: %i[edit update destroy]

  def index
    @clients = current_user.clients
  end

  def new
    @client = Client.new
  end

  def create
    @client = Client.new(client_params)
    if @client.save
      redirect_to clients_path, notice: I18n.t('controllers.clients.create')
    else
      render :new
    end
  end

  def edit
    ###
  end

  def update
    if @client.update(client_params)
      redirect_to clients_path, notice: I18n.t('controllers.clients.update', client_name: @client.name)
    else
      render :edit
    end
  end

  def destroy
    @client.destroy
    redirect_to clients_path, alert: I18n.t('controllers.clients.delete', client_name: @client.name)
  end

  private

  def set_client
    @client = current_user.clients.find(params[:id])
  end

  def client_params
    params.require(:client).permit(:name, :currency_type, :address).merge(user: current_user)
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :authenticate_user!

  before_action :set_contact, only: %i[edit update destroy]

  def index
    @contacts = current_user.contacts
  end

  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contact_params)
    if @contact.save
      redirect_to contacts_path, notice: I18n.t('controllers.contacts.create')
    else
      render :new
    end
  end

  def edit
    ###
  end

  def update
    if @contact.update(contact_params)
      redirect_to contacts_path, notice: I18n.t('controllers.contacts.update')
    else
      render :edit
    end
  end

  def destroy
    @contact.destroy
    redirect_to contacts_url, alert: I18n.t('controllers.contacts.delete')
  end

  private

  def set_contact
    @contact = current_user.contacts.find(params[:id])
  end

  def contact_params
    params.require(:contact).permit(:first_name, :last_name, :email, :office_number, :mobile_number, :client_id).merge(user: current_user)
  end
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  before_action :authenticate_user!

  def index
   # TODO
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!

  before_action :set_project, only: %i[edit update show destroy]

  def index
    @projects = current_user.projects.unarchived
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    if @project.save
      redirect_to projects_path, notice: I18n.t('controllers.projects.create')
    else
      render :new
    end
  end

  def edit
    ####
  end

  def update
    if @project.update(project_params)
      redirect_to projects_path, notice: I18n.t('controllers.projects.update')
    else
      render :edit
    end
  end

  def show
  end

  def destroy
    @project.destroy
    redirect_to projects_url, alert: I18n.t('controllers.projects.delete')
  end

  def archive_project
    project = current_user.projects.find(params["project_id"].to_i)
    project.update(archived: true) if project.present?
    redirect_to projects_path, notice: I18n.t('controllers.projects.archive')
  end

  def unarchive_project
    project = current_user.projects.find(params["project_id"].to_i)
    project.update(archived: false) if project.present?
    redirect_to projects_path, notice: I18n.t('controllers.projects.unarchive')
  end

  private

  def set_project
    @project = current_user.projects.find(params[:id])
  end

  def project_params
    params.require(:project).permit(:name,
                                    :project_code,
                                    :starts_on,
                                    :ends_on,
                                    :total_hours,
                                    :description,
                                    :public,
                                    :client_id,
                                  ).merge(user: current_user)
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :authenticate_user!

  def index
   # TODO
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!

  before_action :set_task, only: %i[edit update destroy]

  def index
    @tasks = Task.all
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    if @task.save
      redirect_to tasks_path, notice: I18n.t('controllers.tasks.create')
    else
      render :new
    end
  end

  def edit
    ###
  end

  def update
    if @task.update(task_params)
      redirect_to tasks_path, notice: I18n.t('controllers.tasks.update')
    else
      render :edit
    end
  end

  def destroy
    @task.destroy
    redirect_to tasks_url, alert: I18n.t('controllers.tasks.delete')
  end

  private

  def set_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:name, :hourly_rate, :billable).merge(user: current_user)
  end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  before_action :authenticate_user!

  def index
   # TODO
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/timesheets_helper.rb
module TimesheetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="css-menubar">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui">

    <title>Tundra Time Tracker</title>

    <link rel="apple-touch-icon" href="/assets/images/apple-touch-icon.png">
    <link rel="shortcut icon" href="/assets/images/favicon.ico">

    <!-- Core -->
    <%= stylesheet_link_tag "/global/css/bootstrap.min.css" %>
    <%= stylesheet_link_tag "/global/css/bootstrap-extend.min.css" %>
    <%= stylesheet_link_tag "/assets/css/site.min.css" %>

    <!-- Plugins -->
    <%= stylesheet_link_tag "/global/vendor/animsition/animsition.css" %>
    <%= stylesheet_link_tag "/global/vendor/animsition/animsition.css" %>
    <%= stylesheet_link_tag "/global/vendor/asscrollable/asScrollable.css" %>
    <%= stylesheet_link_tag "/global/vendor/slidepanel/slidePanel.css" %>
    <%= stylesheet_link_tag "/global/vendor/aspieprogress/asPieProgress.css" %>
    <%= stylesheet_link_tag "/global/vendor/jquery-selective/jquery-selective.css" %>
    <%= stylesheet_link_tag "/global/vendor/bootstrap-datepicker/bootstrap-datepicker.css" %>
    <%= stylesheet_link_tag "/global/vendor/bootstrap-select/bootstrap-select.css" %>
    <%= stylesheet_link_tag "/global/vendor/webui-popover/webui-popover.css" %>
    <%= stylesheet_link_tag "/global/vendor/toolbar/toolbar.css" %>

    <!-- Examples -->
    <%= stylesheet_link_tag "/assets/examples/css/tables/basic.css" %>
    <%= stylesheet_link_tag "/assets/examples/css/pages/project.css" %>
    <%= stylesheet_link_tag "/assets/examples/css/pages/user.css" %>

    <!-- Fonts -->
    <%= stylesheet_link_tag "/global/fonts/web-icons/web-icons.min.css" %>
    <%= stylesheet_link_tag "/global/fonts/brand-icons/brand-icons.min.css" %>
    <%= stylesheet_link_tag "/global/fonts/font-awesome/font-awesome.min.css" %>
    <%= stylesheet_link_tag "http://fonts.googleapis.com/css?family=Roboto:300,400,500,300italic" %>

    <!--[if lt IE 9]>
    <%= javascript_include_tag "/global/vendor/html5shiv/html5shiv.min.js" %>
    <![endif]-->

    <!--[if lt IE 10]>
    <%= javascript_include_tag "/global/vendor/media-match/media.match.min.js" %>
    <%= javascript_include_tag "/global/vendor/respond/respond.min.js" %>
    <![endif]-->

    <!-- Scripts -->
    <%= javascript_include_tag "/global/vendor/breakpoints/breakpoints.js" %>
    <script>
      Breakpoints();
    </script>

    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="animsition site-navbar-small dashboard">

    <!--[if lt IE 8]>
        <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
    <![endif]-->

    <%= render "shared/header" %>

    <%= render "shared/alert" %>

    <%= yield %>
  </body>

  <footer class="site-footer">
    <div class="site-footer-legal">© 2020 Tundra Time Tracker</div>
    <div class="site-footer-right">
      Crafted with <i class="red-600 wb wb-heart"></i> by <a href="https://github.com/danilovelozo">Danilo Velozo</a>
    </div>
  </footer>

  <!-- Core  -->
  <%= javascript_include_tag "/global/vendor/babel-external-helpers/babel-external-helpers.js" %>
  <%= javascript_include_tag "/global/vendor/jquery/jquery.js" %>
  <%= javascript_include_tag "/global/vendor/jquery-ui/jquery-ui.js" %>
  <%= javascript_include_tag "/global/vendor/popper-js/umd/popper.min.js" %>
  <%= javascript_include_tag "/global/vendor/bootstrap/bootstrap.js" %>
  <%= javascript_include_tag "/global/vendor/animsition/animsition.js" %>
  <%= javascript_include_tag "/global/vendor/mousewheel/jquery.mousewheel.js" %>
  <%= javascript_include_tag "/global/vendor/asscrollbar/jquery-asScrollbar.js" %>
  <%= javascript_include_tag "/global/vendor/asscrollable/jquery-asScrollable.js" %>

  <!-- Plugins -->
  <%= javascript_include_tag "/global/vendor/slidepanel/jquery-slidePanel.js" %>
  <%= javascript_include_tag "/global/vendor/aspieprogress/jquery-asPieProgress.js" %>
  <%= javascript_include_tag "/global/vendor/matchheight/jquery.matchHeight-min.js" %>
  <%= javascript_include_tag "/global/vendor/jquery-selective/jquery-selective.min.js" %>
  <%= javascript_include_tag "/global/vendor/bootstrap-datepicker/bootstrap-datepicker.js" %>
  <%= javascript_include_tag "/global/vendor/bootstrap-select/bootstrap-select.js" %>
  <%= javascript_include_tag "/global/vendor/toolbar/jquery.toolbar.js" %>
  <%= javascript_include_tag "/global/vendor/summernote/summernote.min.js" %>
  <%= javascript_include_tag "/global/vendor/asprogress/jquery-asProgress.js" %>


  <!-- Scripts -->
  <%= javascript_include_tag "/global/js/Component.js" %>
  <%= javascript_include_tag "/global/js/Plugin.js" %>
  <%= javascript_include_tag "/global/js/Base.js" %>
  <%= javascript_include_tag "/global/js/Config.js" %>

  <%= javascript_include_tag "/assets/js/Section/Menubar.js" %>
  <%= javascript_include_tag "/assets/js/Section/Sidebar.js" %>
  <%= javascript_include_tag "/assets/js/Section/PageAside.js" %>
  <%= javascript_include_tag "/assets/js/Plugin/menu.js" %>

  <!-- Page -->
  <%= javascript_include_tag "/assets/js/Site.js" %>
  <%= javascript_include_tag "/global/js/Plugin/asscrollable.js" %>
  <%= javascript_include_tag "/global/js/Plugin/slidepanel.js" %>
  <%= javascript_include_tag "/global/js/Plugin/switchery.js" %>
  <%= javascript_include_tag "/global/js/Plugin/matchheight.js" %>
  <%= javascript_include_tag "/global/js/Plugin/aspieprogress.js" %>
  <%= javascript_include_tag "/global/js/Plugin/bootstrap-datepicker.js" %>
  <%= javascript_include_tag "/global/js/Plugin/bootstrap-datepicker.pt-BR.js" %>
  <%= javascript_include_tag "/global/js/Plugin/table.js" %>
  <%= javascript_include_tag "/global/js/Plugin/asprogress.js" %>
  <%= javascript_include_tag "/global/js/Plugin/responsive-tabs.js" %>
  <%= javascript_include_tag "/global/js/Plugin/tabs.js" %>

  <!-- Examples -->
  <%= javascript_include_tag "/assets/examples/js/dashboard/team.js" %>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html class="css-menubar">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui">

    <title>Tundra Time Tracker</title>

    <link rel="apple-touch-icon" href="/assets/images/apple-touch-icon.png">
    <link rel="shortcut icon" href="/assets/images/favicon.ico">

    <!-- Core -->
    <%= stylesheet_link_tag "/global/css/bootstrap.min.css" %>
    <%= stylesheet_link_tag "/global/css/bootstrap-extend.min.css" %>
    <%= stylesheet_link_tag "/assets/css/site.min.css" %>

    <!-- Plugins -->
    <%= stylesheet_link_tag "/global/vendor/animsition/animsition.css" %>
    <%= stylesheet_link_tag "/global/vendor/animsition/animsition.css" %>
    <%= stylesheet_link_tag "/global/vendor/asscrollable/asScrollable.css" %>
    <%= stylesheet_link_tag "/global/vendor/slidepanel/slidePanel.css" %>

    <!-- Examples -->
    <%= stylesheet_link_tag "/assets/examples/css/pages/login.css" %>

    <!-- Fonts -->
    <%= stylesheet_link_tag "/global/fonts/web-icons/web-icons.min.css" %>
    <%= stylesheet_link_tag "/global/fonts/brand-icons/brand-icons.min.css" %>
    <%= stylesheet_link_tag "/global/fonts/font-awesome/font-awesome.min.css" %>
    <%= stylesheet_link_tag "http://fonts.googleapis.com/css?family=Roboto:300,400,500,300italic" %>

    <!--[if lt IE 9]>
    <%= javascript_include_tag "/global/vendor/html5shiv/html5shiv.min.js" %>
    <![endif]-->

    <!--[if lt IE 10]>
    <%= javascript_include_tag "/global/vendor/media-match/media.match.min.js" %>
    <%= javascript_include_tag "/global/vendor/respond/respond.min.js" %>
    <![endif]-->

    <!-- Scripts -->
    <%= javascript_include_tag "/global/vendor/breakpoints/breakpoints.js" %>
    <script>
      Breakpoints();
    </script>

    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="page-login layout-full page-dark">
    <!--[if lt IE 8]>
        <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
    <![endif]-->

    <%= render "shared/alert" %>

    <%= yield %>
  </body>

  <!-- Core  -->
  <%= javascript_include_tag "/global/vendor/babel-external-helpers/babel-external-helpers.js" %>
  <%= javascript_include_tag "/global/vendor/jquery/jquery.js" %>
  <%= javascript_include_tag "/global/vendor/popper-js/umd/popper.min.js" %>
  <%= javascript_include_tag "/global/vendor/bootstrap/bootstrap.js" %>
  <%= javascript_include_tag "/global/vendor/animsition/animsition.js" %>
  <%= javascript_include_tag "/global/vendor/mousewheel/jquery.mousewheel.js" %>
  <%= javascript_include_tag "/global/vendor/asscrollbar/jquery-asScrollbar.js" %>
  <%= javascript_include_tag "/global/vendor/asscrollable/jquery-asScrollable.js" %>

  <!-- Plugins -->
  <%= javascript_include_tag "/global/vendor/slidepanel/jquery-slidePanel.js" %>

  <!-- Scripts -->
  <%= javascript_include_tag "/global/js/Component.js" %>
  <%= javascript_include_tag "/global/js/Plugin.js" %>
  <%= javascript_include_tag "/global/js/Base.js" %>
  <%= javascript_include_tag "/global/js/Config.js" %>

  <!-- Config -->
  <%= javascript_include_tag "/global/js/config/colors.js" %>
  <script>Config.set('assets', '../assets');</script>

  <!-- Page -->
  <%= javascript_include_tag "/assets/js/Site.js" %>
  <%= javascript_include_tag "/global/js/Plugin/tabs.js" %>

</html>

app/views/shared/_alert.html.erb
<% if flash[:notice] %>
  <div class="alert alert-alt alert-success alert-dismissible" role="alert">
    <a class="alert-link" href="javascript:void(0)"><%= flash[:notice] %></a>
  </div>
<% end %>

<% if flash[:alert] %>
  <div class="alert alert-alt alert-danger alert-dismissible" role="alert">
    <a class="alert-link" href="javascript:void(0)"><%= flash[:alert] %></a>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="site-footer">
  <div class="site-footer-legal">© 2020 Tundra Time Tracker</div>
  <div class="site-footer-right">
    Crafted with <i class="red-600 wb wb-heart"></i> by <a href="https://danilovelozo.github.io/about/">Danilo Velozo</a>
  </div>
</footer>

app/views/shared/_header.html.erb
<nav class="site-navbar navbar navbar-inverse bg-blue-grey-700 navbar-fixed-top navbar-mega navbar-inverse"
  role="navigation">

  <div class="navbar-header">
    <button type="button" class="navbar-toggler hamburger hamburger-close navbar-toggler-left hided"
      data-toggle="menubar">
      <span class="sr-only">Toggle navigation</span>
      <span class="hamburger-bar"></span>
    </button>
    <button type="button" class="navbar-toggler collapsed" data-target="#site-navbar-collapse"
      data-toggle="collapse">
      <i class="icon wb-more-horizontal" aria-hidden="true"></i>
    </button>
    <div class="navbar-brand navbar-brand-center">

      <img class="navbar-brand-logo navbar-brand-logo-normal" src="/assets/images/logo.png"
        title="Tundra Time Tracker">

      <img class="navbar-brand-logo navbar-brand-logo-special" src="/assets/images/logo-colored.png"
        title="Tundra Time Tracker">

      <span class="navbar-brand-text hidden-xs-down"> Tundra Time Tracker </span>
    </div>
  </div>

  <div class="navbar-container container-fluid">
    <div class="collapse navbar-collapse navbar-collapse-toolbar" id="site-navbar-collapse">
      <ul class="nav navbar-toolbar">
        <li class="nav-item hidden-float" id="toggleMenubar">
          <a class="nav-link" data-toggle="menubar" href="#" role="button">
            <i class="icon hamburger hamburger-arrow-left">
              <span class="sr-only">Toggle menubar</span>
              <span class="hamburger-bar"></span>
            </i>
          </a>
        </li>
      </ul>

      <ul class="nav navbar-toolbar navbar-right navbar-toolbar-right">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" aria-expanded="false"
            role="button">Olá, <%= current_user.first_name %></a>
            <div class="dropdown-menu" role="menu">
              <%= link_to edit_user_registration_path, class: "dropdown-item", method: :get do %>
                <i class="icon wb-user" aria-hidden="true"></i> Perfil
              <% end %>

              <div class="dropdown-divider" role="presentation"></div>

              <%= link_to destroy_user_session_path, class: "dropdown-item", method: :delete do %>
                <i class="icon wb-power" aria-hidden="true"></i> Sair
              <% end %>
            </div>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link" data-toggle="dropdown" href="javascript:void(0)" title="Notifications"
            aria-expanded="false" data-animation="scale-up" role="button">
            <i class="icon wb-bell" aria-hidden="true"></i>
            <span class="badge badge-pill badge-danger up">1</span>
          </a>
          <div class="dropdown-menu dropdown-menu-right dropdown-menu-media" role="menu">
            <div class="dropdown-menu-header">
              <h5>NOTIFICAÇÕES</h5>
              <span class="badge badge-round badge-danger">1</span>
            </div>

            <div class="list-group">
              <div data-role="container">
                <div data-role="content">
                  <a class="list-group-item dropdown-item" href="javascript:void(0)" role="menuitem">
                    <div class="media">
                      <div class="pr-10">
                        <i class="icon wb-order bg-red-600 white icon-circle" aria-hidden="true"></i>
                      </div>
                      <div class="media-body">
                        <h6 class="media-heading">Mensagem de notificação aqui</h6>
                        <time class="media-meta" datetime="2018-06-12T20:50:48+08:00">5 horas atrás</time>
                      </div>
                    </div>
                  </a>
                </div>
              </div>
            </div>
            <div class="dropdown-menu-footer">
              <a class="dropdown-menu-footer-btn" href="javascript:void(0)" role="button">
                <i class="icon wb-settings" aria-hidden="true"></i>
              </a>
              <a class="dropdown-item" href="javascript:void(0)" role="menuitem">
                Mostrar todas
              </a>
            </div>
          </div>
        </li>

        <!-- Partial de Mensagens Aqui -->

      </ul>
    </div>
  </div>
</nav>
<div class="site-menubar site-menubar-light">
  <%= render "shared/menu" %>
</div>

app/views/shared/_menu.html.erb
<div class="site-menubar-body">
  <div>
    <div>
      <ul class="site-menu" data-plugin="menu">

        <li class="site-menu-item ">
          <%= link_to timesheets_path, class: "animsition-link", method: :get do %>
            <i class="site-menu-icon wb-time" aria-hidden="true"></i>
            <span class="site-menu-title">Controle de horas</span>
          <% end %>
        </li>

        <li class="site-menu-item ">
          <%= link_to projects_path, class: "animsition-link", method: :get do %>
            <i class="site-menu-icon wb-briefcase" aria-hidden="true"></i>
            <span class="site-menu-title">Projetos</span>
          <% end %>
        </li>

        <li class="site-menu-item ">
          <%= link_to expenses_path, class: "animsition-link", method: :get do %>
            <i class="site-menu-icon wb-tag" aria-hidden="true"></i>
            <span class="site-menu-title">Despesas</span>
          <% end %>
        </li>

        <li class="site-menu-item ">
          <%= link_to teams_path, class: "animsition-link", method: :get do %>
            <i class="site-menu-icon wb-users" aria-hidden="true"></i>
            <span class="site-menu-title">Equipes</span>
          <% end %>
        </li>

        <li class="site-menu-item ">
          <%= link_to reports_path, class: "animsition-link", method: :get do %>
            <i class="site-menu-icon wb-stats-bars" aria-hidden="true"></i>
            <span class="site-menu-title">Relatórios</span>
          <% end %>
        </li>

        <li class="dropdown site-menu-item has-sub">
          <a data-toggle="dropdown" href="javascript:void(0)" data-dropdown-toggle="false">
            <i class="site-menu-icon wb-settings" aria-hidden="true"></i>
            <span class="site-menu-title">Gerenciar</span>
            <span class="site-menu-arrow"></span>
          </a>
          <div class="dropdown-menu">
            <div class="site-menu-scroll-wrap is-list">
              <div>
                <div>
                  <ul class="site-menu-sub site-menu-normal-list">
                    <li class="site-menu-item">
                      <%= link_to clients_path, class: "animsition-link", method: :get do %>
                        <span class="site-menu-title">Clientes</span>
                      <% end %>
                    </li>
                    <li class="site-menu-item">
                      <%= link_to contacts_path, class: "animsition-link", method: :get do %>
                        <span class="site-menu-title">Contatos</span>
                      <% end %>
                    </li>
                    <li class="site-menu-item">
                      <%= link_to tasks_path, class: "animsition-link", method: :get do %>
                        <span class="site-menu-title">Tarefas</span>
                      <% end %>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </li>

      </ul>
    </div>
  </div>
</div>