config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '',
                     path_names: { sign_in: 'entrar',
                                   sign_out: 'sair',
                                   sign_up: 'cadastro' }

  root 'projects#index'

  resources :clients

  resources :contacts

  resources :tasks

  resources :timesheets

  resources :expenses
  
  resources :teams

  resources :reports

  resources :projects do
    post 'archive',   to: 'projects#archive_project',   as: :archive
    post 'unarchive', to: 'projects#unarchive_project', as: :unarchive
  end
end

app/models/client.rb
class Client < ApplicationRecord
  CURRENCY_TYPE = ['R$ BRL', '$ USD', '€ EUR'].freeze

  has_many :contacts, dependent: :destroy
  has_many :projects, dependent: :destroy

  belongs_to :user

  validates :name, presence: true
  validates :currency_type, presence: true
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :authenticate_user!

  before_action :set_client, only: %i[edit update destroy]

  def index
    @clients = current_user.clients
  end

  def new
    @client = Client.new
  end

  def create
    @client = Client.new(client_params)
    if @client.save
      redirect_to clients_path, notice: I18n.t('controllers.clients.create')
    else
      render :new
    end
  end

  def edit
    ###
  end

  def update
    if @client.update(client_params)
      redirect_to clients_path, notice: I18n.t('controllers.clients.update', client_name: @client.name)
    else
      render :edit
    end
  end

  def destroy
    @client.destroy
    redirect_to clients_path, alert: I18n.t('controllers.clients.delete', client_name: @client.name)
  end

  private

  def set_client
    @client = current_user.clients.find(params[:id])
  end

  def client_params
    params.require(:client).permit(:name, :currency_type, :address).merge(user: current_user)
  end
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/_client.html.erb
<tr>
  <td><%= client.name %></td>
  <td>
    <span class="text-muted"><i class="wb wb-time"></i> <%= client.created_at.strftime('%d/%m/%Y') %></span>
  </td>
  <td><%= client.currency_type %></td>
  <td class="text-nowrap">

    <%= link_to edit_client_path(client), class: "btn btn-outline btn-success btn-xs", method: :get do %>
      <span><i class="icon wb-edit" aria-hidden="true"></i>Editar</span>
    <% end %>

    <%= link_to client, class: "btn btn-outline btn-danger btn-xs", method: :delete, data: { confirm: 'Tem certeza que deseja excluir este cliente?' } do %>
      <span><i class="icon wb-close" aria-hidden="true"></i>Excluir</span>
    <% end %>

  </td>
</tr>

app/views/clients/_form.html.erb
<%= form_for @client, html: { class: "form-horizontal", "data-parsley-validate" => true } do |f|  %>

  <% if f.object.errors.any? %>
    <ul>
      <% f.object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>

  <div class="form-group row">
    <label class="col-md-3 form-control-label">Nome: </label>
    <div class="col-md-9">
      <%= f.text_field :name, class: "form-control", 'data-parsley-required' => 'true', 'data-parsley-required-message' => 'Campo obrigatório.' %>
    </div>
  </div>

  <div class="form-group row">
    <label class="col-md-3 form-control-label">Endereço <span class="text-muted">(opcional)</span>: </label>
    <div class="col-md-9">
      <%= f.text_field :address, class: "form-control" %>
    </div>
  </div>

  <div class="form-group row">
    <label class="col-md-3 form-control-label">Tipo de Moeda: </label>
    <div class="col-md-9">
      <%= f.select(:currency_type, options_for_select(Client::CURRENCY_TYPE, selected: @client.currency_type), {include_blank: "Selecione uma opção"}, {class: "show-tick", 'data-plugin': "selectpicker", 'data-parsley-required' => 'true', 'data-parsley-required-message' => 'Campo obrigatório.'}) %>
    </div>
  </div>

  <div class="form-group row">
    <div class="col-md-9 offset-md-3">
      <%= f.submit "Salvar", class: "btn btn-primary" %>
      <%= link_to "Cancelar", clients_path, class: "btn btn-default btn-outline", method: :get %>
    </div>
  </div>
<% end %>

app/views/clients/edit.html.erb
<div class="page">
  <div class="page-header">
    <h1 class="page-title">Editar Cliente</h1>
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="/">Início</a></li>
      <li class="breadcrumb-item active">Editar Cliente</li>
    </ol>
  </div>

  <div class="page-content">
    <div class="panel">
      <header class="panel-heading">
        <h3 class="panel-title">
          Editar <%= @client.name %>
        </h3>
      </header>
      <div class="panel-body container-fluid">
        <div class="row row-lg">
          <div class="col-md-12 col-lg-9">
              <div class="example">
                <%= render "form" %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/clients/index.html.erb
<div class="page">
  <div class="page-header">
    <h1 class="page-title">Clientes</h1>
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="/">Início</a></li>
      <li class="breadcrumb-item active">Clientes</li>
    </ol>
    <div class="page-header-actions">
      <%= link_to new_client_path, class: "btn btn-animate btn-animate-side btn-success btn-sm", method: :get do %>
        <i class="icon wb-plus" aria-hidden="true"></i>Novo Cliente
      <% end %>

      <% if @clients.present? %>
        <%= link_to new_contact_path, class: "btn btn-animate btn-animate-side btn-info btn-sm", method: :get do %>
          <i class="icon wb-plus" aria-hidden="true"></i>Adicionar Contato
        <% end %>
      <% end %>
    </div>
  </div>

  <div class="page-content">
    <div class="panel">
      <div class="panel-body">
        <div class="example-wrap">
          <h4 class="example-title">Gerenciar Clientes</h4>
          <% if @clients.present? %>
            <div class="example">
              <div class="table-responsive">
                <table class="table">
                  <thead>
                    <tr>
                      <th>Cliente</th>
                      <th>Data de criação</th>
                      <th>Tipo de moeda</th>
                      <th>Ações</th>
                    </tr>
                  </thead>
                  <tbody>
                    <%= render @clients %>
                  </tbody>
                </table>
              </div>
            </div>
          <% else %>
            <p>Você não possui clientes cadastrados.</p>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/clients/new.html.erb
<div class="page">
  <div class="page-header">
    <h1 class="page-title">Novo Cliente</h1>
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="/">Início</a></li>
      <li class="breadcrumb-item active">Novo Cliente</li>
    </ol>
  </div>

  <div class="page-content">
    <div class="panel">
      <header class="panel-heading">
        <h3 class="panel-title">
          Cadastrar Novo Cliente
        </h3>
      </header>
      <div class="panel-body container-fluid">
        <div class="row row-lg">
          <div class="col-md-12 col-lg-9">
              <div class="example">
                <%= render "form" %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>