config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '',
                     path_names: { sign_in: 'entrar',
                                   sign_out: 'sair',
                                   sign_up: 'cadastro' }

  root 'projects#index'

  resources :clients

  resources :contacts

  resources :tasks

  resources :timesheets

  resources :expenses
  
  resources :teams

  resources :reports

  resources :projects do
    post 'archive',   to: 'projects#archive_project',   as: :archive
    post 'unarchive', to: 'projects#unarchive_project', as: :unarchive
  end
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :client
  belongs_to :user
  has_many :timesheets, dependent: :destroy

  validates :name, presence: true
  validates :total_hours, presence: true

  scope :archived,   -> { where(archived: true) }
  scope :unarchived, -> { where(archived: false) }
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!

  before_action :set_project, only: %i[edit update show destroy]

  def index
    @projects = current_user.projects.unarchived
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    if @project.save
      redirect_to projects_path, notice: I18n.t('controllers.projects.create')
    else
      render :new
    end
  end

  def edit
    ####
  end

  def update
    if @project.update(project_params)
      redirect_to projects_path, notice: I18n.t('controllers.projects.update')
    else
      render :edit
    end
  end

  def show
  end

  def destroy
    @project.destroy
    redirect_to projects_url, alert: I18n.t('controllers.projects.delete')
  end

  def archive_project
    project = current_user.projects.find(params["project_id"].to_i)
    project.update(archived: true) if project.present?
    redirect_to projects_path, notice: I18n.t('controllers.projects.archive')
  end

  def unarchive_project
    project = current_user.projects.find(params["project_id"].to_i)
    project.update(archived: false) if project.present?
    redirect_to projects_path, notice: I18n.t('controllers.projects.unarchive')
  end

  private

  def set_project
    @project = current_user.projects.find(params[:id])
  end

  def project_params
    params.require(:project).permit(:name,
                                    :project_code,
                                    :starts_on,
                                    :ends_on,
                                    :total_hours,
                                    :description,
                                    :public,
                                    :client_id,
                                  ).merge(user: current_user)
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_for @project, html: { class: "form-horizontal", "data-parsley-validate" => true } do |f|  %>

  <% if f.object.errors.any? %>
    <ul>
      <% f.object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>

  <div class="form-group row">
    <label class="col-md-3 form-control-label">Cliente: </label>
    <div class="col-md-9">
      <%= f.select(:client_id, options_for_select(current_user.clients.map {|client| [client.name, client.id]}, :selected => f.object.client_id), {include_blank: "Selecione uma opção"}, {class: "show-tick", 'data-plugin': "selectpicker", 'data-parsley-required' => 'true', 'data-parsley-required-message' => 'Campo obrigatório.'}) %>
    </div>
  </div>

  <div class="form-group row">
    <label class="col-md-3 form-control-label">Nome: </label>
    <div class="col-md-6">
      <%= f.text_field :name, class: "form-control", 'data-parsley-required' => 'true', 'data-parsley-required-message' => 'Campo obrigatório.' %>
    </div>
  </div>

  <div class="form-group row">
    <label class="col-md-3 form-control-label">Código Projeto <span class="text-muted">(opcional)</span>: </label>
    <div class="col-md-6">
      <%= f.text_field :project_code, class: "form-control" %>
    </div>
  </div>

  <div class="form-group row">
    <label class="col-md-3 form-control-label">Qtd. Horas: </label>
    <div class="col-md-6">
      <%= f.text_field :total_hours, class: "form-control", 'data-parsley-required' => 'true', 'data-parsley-required-message' => 'Campo obrigatório.' %>
    </div>
  </div>

  <div class="form-group row">
    <label class="col-md-3 form-control-label">Data <span class="text-muted">(opcional)</span>: </label>
    <div class="col-md-3">
      <div class="input-group">
        <span class="input-group-addon">
          <i class="icon wb-calendar" aria-hidden="true"></i>
        </span>
          <%= f.text_field :starts_on, class: "custom-datepicker form-control", placeholder: "Início", "data-plugin" => "datepicker" %>
      </div>
    </div>

    <div class="col-md-3">
      <div class="input-group">
        <span class="input-group-addon">
          <i class="icon wb-calendar" aria-hidden="true"></i>
        </span>
          <%= f.text_field :ends_on, class: "custom-datepicker form-control", placeholder: "Término", "data-plugin" => "datepicker" %>
      </div>
    </div>
  </div>

  <div class="form-group row">
    <label class="col-md-3 form-control-label">Descrição <span class="text-muted">(opcional)</span>: </label>
    <div class="col-md-6">
      <%= f.text_area :description, class: "form-control" %>
    </div>
  </div>

  <div class="form-group row">
    <div class="col-md-9 offset-md-3">
      <%= f.submit "Salvar", class: "btn btn-primary" %>
      <%= link_to "Cancelar", projects_path, class: "btn btn-default btn-outline", method: :get %>
    </div>
  </div>
<% end %>

app/views/projects/_project.html.erb
<tr data-link="<%= project_path(project) %>" style="cursor: pointer;">
  <td><%= project.client.name %></td>
  <td><span class="text-muted"> <%= "[#{project.project_code}]" if project.project_code.present? %></span> <%= project.name %></td>
  <td><%= project.starts_on.present? ? project.starts_on : "N/A" %></td>
  <td><%= project.ends_on.present? ? project.ends_on : "N/A" %></td>
  <td><%= project.total_hours.present? ? project.total_hours : "N/A" %></td>
  <td><%= project.timesheets.present? ? project.timesheets.map(&:duration).sum : "N/A" %></td>
  <td><i class="fa fa-usd"></i> <%= project.timesheets.present? ? number_to_currency(project.timesheets.map(&:duration).sum * project.timesheets.map(&:task)[0].hourly_rate.to_f, unit: "", separator: ",", delimiter: "") : "N/A" %></td>
  <td class="text-nowrap">

    <%= link_to project_path(project), class: "btn btn-outline btn-dark btn-xs", method: :get do %>
      <span><i class="icon wb-settings" aria-hidden="true"></i>Gerenciar</span>
    <% end %>

    <%= link_to edit_project_path(project), class: "btn btn-outline btn-success btn-xs", method: :get do %>
      <span><i class="icon wb-edit" aria-hidden="true"></i>Editar</span>
    <% end %>

    <%= link_to project, class: "btn btn-outline btn-danger btn-xs", method: :delete, data: { confirm: 'Tem certeza que deseja excluir este projeto?' } do %>
      <span><i class="icon wb-close" aria-hidden="true"></i>Excluir</span>
    <% end %>

  </td>
</tr>

app/views/projects/edit.html.erb
<div class="page">
  <div class="page-header">
    <h1 class="page-title">Editar Projeto</h1>
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="/">Início</a></li>
      <li class="breadcrumb-item active">Editar Projeto</li>
    </ol>
  </div>

  <div class="page-content">
    <div class="panel">
      <header class="panel-heading">
        <h3 class="panel-title">
          Editar <%= @project.name %>
        </h3>
      </header>
      <div class="panel-body container-fluid">
        <div class="row row-lg">
          <div class="col-md-12 col-lg-9">
              <div class="example">
                <%= render "form" %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/projects/index.html.erb
<div class="page">
  <div class="page-header">
    <h1 class="page-title">Projetos</h1>
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="/">Início</a></li>
      <li class="breadcrumb-item active">Projetos</li>
    </ol>
    <div class="page-header-actions">
      <%= link_to new_project_path, class: "btn btn-animate btn-animate-side btn-success btn-sm", method: :get do %>
        <i class="icon wb-plus" aria-hidden="true"></i>Novo Projeto
      <% end %>
    </div>
  </div>

  <div class="page-content">
    <div class="panel">
      <div class="panel-body">
        <div class="example-wrap">
          <h4 class="example-title">Gerenciar Projetos</h4>
          <% if @projects.present? %>
            <div class="example">
              <div class="table-responsive table-hover">
                <table class="table">
                  <thead>
                    <tr>
                      <th>Cliente</th>
                      <th>Nome</th>
                      <th>Inicia em</th>
                      <th>Termina em</th>
                      <th>Horas totais</th>
                      <th>Horas trabalhadas</th>
                      <th>Valor total</th>
                      <th></th>
                    </tr>
                  </thead>
                  <tbody>
                    <%= render @projects %>
                  </tbody>
                </table>
              </div>
            </div>
          <% else %>
            <p>Você não possui projetos cadastrados.</p>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/projects/new.html.erb
<div class="page">
  <div class="page-header">
    <h1 class="page-title">Novo Projeto</h1>
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="/">Início</a></li>
      <li class="breadcrumb-item active">Novo Projeto</li>
    </ol>
  </div>

  <div class="page-content">
    <div class="panel">
      <header class="panel-heading">
        <h3 class="panel-title">
          Cadastrar Novo Projeto
        </h3>
      </header>
      <div class="panel-body container-fluid">
        <div class="row row-lg">
          <div class="col-md-12 col-lg-9">
              <div class="example">
                <%= render "form" %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/projects/show.html.erb
<div class="page">
  <div class="page-content">
    <div class="row">
      <div class="col-xxl-9 col-xl-8 col-lg-12">
        <div class="card">
          <div class="card-block">
            <h4 class="card-title project-title">
              <%= @project.name %>
              <!-- <btn class="btn btn-pure btn-default icon wb-pencil btn-edit"></btn> -->
            </h4>
            <p class="card-text">

            </p>
            <p class="card-text">
                Cliente: <%= link_to @project.client.name, edit_client_path(@project.client.id), method: :get %>
            </p>
            <p class="card-text">
              <% if @project.starts_on.present? || @project.ends_on.present? %>
                <span class="text-muted"><i class="icon wb-calendar" aria-hidden="true"></i>
                  <%= @project.starts_on %> - <%= @project.ends_on %>
                </span>
              <% end %>
            </p>
            <% if @project.description.present? %>
              <p class="card-text">
                <%= @project.description %>
              </p>
            <% end %>
          </div>
          <div class="card-block"><hr></div>

          <div class="card-block ">
            <div class="project-controls clearfix">
              <div class="float-right">
                <%= link_to edit_project_path(@project), class: "btn btn-outline btn-default", method: :get do %>
                  <span><i class="icon wb-pencil" aria-hidden="true"></i>Editar projeto</span>
                <% end %>

                <div class="dropdown">
                  <button type="button" class="btn btn-default btn-outline dropdown-toggle mr-0"
                    data-toggle="dropdown" aria-expanded="true">
                    Ações
                  </button>
                  <div class="dropdown-menu">
                    <%= link_to @project, class: "dropdown-item", method: :delete, data: { confirm: 'Tem certeza que deseja excluir este projeto?' } do %>
                      Excluir
                    <% end %>
                  </div>
                </div>
              </div>
            </div>
          </div>

            <div class="col-lg-12 masonry-item">
              <div class="panel" id="daily-feed">
                <div class="panel-heading">
                  <h3 class="panel-title"><span><i class="icon wb-clipboard" aria-hidden="true"></i>Tarefas</span></h3>
                </div>
                <div class="panel-body">
                  <ul class="list-group list-group-dividered list-group-full">
                    <li class="list-group-item">
                      <% if @project.timesheets.present? %>
                        <% @project.timesheets.order("created_at desc").each do |project_timesheet| %>
                        <div class="media">
                          <div class="media-body">
                            <h5 class="mt-0 mb-10">
                              <span><i class="icon wb-calendar" aria-hidden="true"></i><%= project_timesheet.start_date %></span>
                            </h5>
                            <h5 class="mt-0 mb-5">
                              <% if project_timesheet.duration.present? %>
                                <span class="float-right"><%= project_timesheet.duration %> h</span>
                              <% end %>
                            </h5>
                            <p><%= project_timesheet.description %></p>
                            <small><span><i class="icon wb-list" aria-hidden="true"></i>Tarefa:</span>
                              <%= link_to project_timesheet.task.name, edit_task_path(project_timesheet.task.id), style: "color: #77838E;", method: :get %>
                            </small><br>
                            <% if project_timesheet.external_url.present? %>
                              <small>
                                <span><i class="icon wb-link" aria-hidden="true"></i>URL Externa:</span> <%= project_timesheet.external_url %>
                              </small><br>
                            <% end %>
                            <small><span><i class="icon wb-time" aria-hidden="true"></i>
                              <% if project_timesheet.work_to.present? %>
                                <%= project_timesheet.work_from %> até <%= project_timesheet.work_to %>
                              <% else %>
                                Em andamento
                              <% end %>
                            </small>
                            <div class="actions mt-10">
                              <%= link_to edit_timesheet_path(project_timesheet), class: "btn btn-outline btn-default btn-xs", method: :get do %>
                                <i class="icon wb-pencil" aria-hidden="true"></i>Editar
                              <% end %>
                              <hr>
                            </div>
                          </div>
                        </div>
                        <% end %>
                      <% else %>
                      <div class="media">
                        <div class="media-body">
                          <p class="mt-0 mb-10">
                            Não há tarefas cadastradas.
                          </p>
                        </div>
                      </div>
                      <% end %>
                    </li>
                  </ul>
                  <!-- <button type="button" class="btn btn-block btn-primary"><i class="icon wb-chevron-down mr-5" aria-hidden="true"></i>Show
                    More</button> -->
                </div>
            </div>
          </div>
        </div>
      </div>
      <div class="col-xxl-3 col-xl-4 col-lg-12">
        <div class="card">
          <div class="card-block">
            <p class="mb-10">
              <span class="float-right pl-10 text-muted"><%= @project.project_code %></span>
              Código do projeto
            </p>
            <p class="mb-10">
              <span class="float-right pl-10"><%= @project.total_hours %> horas</span>
              Total de horas
            </p>
            <p>
              <span class="float-right pl-10"><%= @project.timesheets.map(&:duration).sum if @project.timesheets.present? %> horas</span>
              Horas trabalhadas
            </p>
            </ul>
            <div class="progress progress-lg">
              <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="<%= @project.timesheets.map(&:duration).sum if @project.timesheets.present? %>" aria-valuemin="0" aria-valuemax="<%= @project.total_hours %>" style="width: <%= @project.timesheets.map(&:duration).sum if @project.timesheets.present? %>%;">
              </div>
            </div>
          </div>

          <div class="card card-block p-30">
            <div class="counter counter-lg">
              <div class="counter-label text-uppercase">Valor total (<%= @project.client.currency_type.split.first %>)</div>
              <div class="counter-number-group">
                <span class="counter-icon mr-10 green-600">
                  <i class="fa fa-dollar"></i>
                </span>
                <%if @project.timesheets.present? %>
                  <span class="counter-number"><%= number_to_currency(@project.timesheets.map(&:duration).sum * @project.timesheets.map(&:task)[0].hourly_rate.to_f, unit: "", separator: ",", delimiter: "")%></span>
                <% end %>
              </div>
            </div>
          </div>

          <div class="card-block project-dates">
            <p class="mb-10">
              <span>Data de criação:</span>
              <%= @project.created_at.strftime('%d/%m/%Y') %>
            </p>
            <p class="mb-10">
              <span>Atualizado em:</span>
              <%= @project.updated_at.strftime('%d/%m/%Y')%>
            </p>
          </div>
          <div class="card-block project-fast-operation">
          <%- unless @project.archived? %>
            <%= link_to project_archive_path(@project), method: :post, data: { confirm: 'Tem certeza que deseja arquivar este projeto?' } do %>
              <i class="icon wb-folder mr-10"></i> Arquivar projeto
            <% end %>
          <%- end %>

          <%- if @project.archived? %>
            <%= link_to project_unarchive_path(@project), method: :post, data: { confirm: 'Tem certeza que deseja ativar este projeto novamente?' } do %>
              <i class="icon wb-tag mr-10"></i> Desarquivar projeto
            <% end %>
          <%- end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>