config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '',
                     path_names: { sign_in: 'entrar',
                                   sign_out: 'sair',
                                   sign_up: 'cadastro' }

  root 'projects#index'

  resources :clients

  resources :contacts

  resources :tasks

  resources :timesheets

  resources :expenses
  
  resources :teams

  resources :reports

  resources :projects do
    post 'archive',   to: 'projects#archive_project',   as: :archive
    post 'unarchive', to: 'projects#unarchive_project', as: :unarchive
  end
end

app/models/timesheet.rb
class Timesheet < ApplicationRecord
  belongs_to :project
  belongs_to :task
  belongs_to :user

  validates :description, presence: true
  validates :start_date, presence: true
end

app/controllers/timesheets_controller.rb
class TimesheetsController < ApplicationController
  before_action :authenticate_user!

  before_action :set_timesheet, only: %i[edit update show destroy]

  def index
    @timesheets = current_user.timesheets.page(params[:page]).per(10)
  end

  def new
    @timesheet = Timesheet.new
  end

  def create
    @timesheet = Timesheet.new(timesheet_params)
    if @timesheet.save
      redirect_to timesheets_path, notice: I18n.t('controllers.timesheets.create')
    else
      render :new
    end
  end

  def edit
    # TODO
  end

  def update
    if @timesheet.update(timesheet_params)
      redirect_to timesheets_path, notice: I18n.t('controllers.timesheets.update')
    else
      render :edit
    end
  end

  def show
  end

  def destroy
    @timesheet.destroy
    redirect_to timesheets_path, alert: I18n.t('controllers.timesheets.delete')
  end

  private

  def set_timesheet
    @timesheet = current_user.timesheets.find(params[:id])
  end

  def timesheet_params
    params.require(:timesheet).permit(:description,
                                      :start_date,
                                      :work_from,
                                      :work_to,
                                      :duration,
                                      :external_url,
                                      :project_id,
                                      :task_id,
                                     ).merge(user: current_user)
  end
end

app/helpers/timesheets_helper.rb
module TimesheetsHelper
end

app/views/timesheets/_form.html.erb
<%= form_for @timesheet, html: { class: "form-horizontal", "data-parsley-validate" => true } do |f|  %>

  <% if f.object.errors.any? %>
    <ul>
      <% f.object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>

  <div class="form-group row">
    <label class="col-md-3 form-control-label">Projeto: </label>
    <div class="col-md-6">
      <%= f.select(:project_id, options_for_select(current_user.projects.unarchived.map {|project| [project.name, project.id]}, :selected => f.object.project_id), {include_blank: "Selecione uma opção"}, {class: "form-control", 'data-plugin': "selectpicker", 'data-parsley-required' => 'true', 'data-parsley-required-message' => 'Campo obrigatório.'}) %>
    </div>
  </div>

  <div class="form-group row">
    <label class="col-md-3 form-control-label">Tarefa: </label>
    <div class="col-md-6">
      <%= f.select(:task_id, options_for_select(current_user.tasks.map {|task| [task.name, task.id]}, :selected => f.object.task_id), {include_blank: "Selecione uma opção"}, {class: "form-control", 'data-plugin': "selectpicker", 'data-parsley-required' => 'true', 'data-parsley-required-message' => 'Campo obrigatório.'}) %>
    </div>
  </div>

  <div class="form-group row">
    <label class="col-md-3 form-control-label">Descrição <span class="text-muted">(opcional)</span>: </label>
    <div class="col-md-6">
      <%= f.text_area :description, class: "form-control" %>
    </div>
  </div>

  <div class="form-group row">
    <label class="col-md-3 form-control-label">Data de início: </label>
    <div class="col-md-3">
      <div class="input-group">
        <span class="input-group-addon">
          <i class="icon wb-calendar" aria-hidden="true"></i>
        </span>
          <%= f.text_field :start_date, class: "custom-datepicker form-control", "data-plugin" => "datepicker", 'data-parsley-required' => 'true', 'data-parsley-required-message' => 'Campo obrigatório.' %>
      </div>
    </div>
  </div>

  <div class="form-group row">
    <label class="col-md-3 form-control-label">Trabalhou de: </label>
    <div class="col-md-3">
      <div class="input-group">
        <span class="input-group-addon">
          <i class="icon wb-time" aria-hidden="true"></i>
        </span>
          <%= f.text_field :work_from, class: "time-mask form-control", placeholder: "Início", id: "timesheet-start-time" %>
      </div>
    </div>

    <div class="col-md-3">
      <div class="input-group">
        <span class="input-group-addon">
          <i class="icon wb-time" aria-hidden="true"></i>
        </span>
          <%= f.text_field :work_to, class: "time-mask form-control", placeholder: "Fim", id: "timesheet-end-time" %>
      </div>
    </div>
  </div>

  <div class="form-group row">
    <label class="col-md-3 form-control-label">Duração: </label>
    <div class="col-md-3">
      <%= f.text_field :duration, class: "form-control", id: "timesheet-duration" %>
    </div>
  </div>

  <div class="form-group row">
    <label class="col-md-3 form-control-label">Link externo <span class="text-muted">(opcional)</span>: </label>
    <div class="col-md-6">
      <div class="input-group">
        <span class="input-group-addon">
          <i class="icon wb-link" aria-hidden="true"></i>
        </span>
          <%= f.text_field :external_url, class: "form-control" %>
      </div>
    </div>
  </div>

  <div class="form-group row">
    <div class="col-md-6 offset-md-3">
      <%= f.submit "Salvar", class: "btn btn-primary" %>
      <%= link_to "Cancelar", timesheets_path, class: "btn btn-default btn-outline", method: :get %>
    </div>
  </div>
<% end %>

app/views/timesheets/_timesheet.html.erb
<div class="tab-pane animation-fade active" id="all_contacts" role="tabpanel">
  <ul class="list-group">
    <li class="list-group-item">
      <div class="media">
        <!-- <div class="pr-0 pr-sm-20 align-self-center">
          <div class="avatar avatar-online">
            <img src="../../../global/portraits/1.jpg" alt="...">
            <i class="avatar avatar-busy"></i>
          </div>
        </div> -->
        <div class="media-body align-self-center">
          <h5 class="mt-0 mb-10">
            <span><i class="icon wb-calendar" aria-hidden="true"></i><%= timesheet.start_date %></span>
          </h5>
          <h5 class="mt-0 mb-5">
            <%= "[#{timesheet.project.project_code}]" if timesheet.project.project_code.present? %> <%= link_to timesheet.project.name, project_path(timesheet.project.id), style: "color: #77838E;", method: :get %>
            <small>(<%= link_to timesheet.project.client.name, edit_client_path(timesheet.project.client.id) , style: "color: #77838E;", method: :get %>)</small>
          </h5>
          <p>
            <%= timesheet.description %>
          </p>
          <small><span><i class="icon wb-list" aria-hidden="true"></i>Tarefa:</span> <%= link_to timesheet.task.name, edit_task_path(timesheet.task.id), style: "color: #77838E;", method: :get %></small><br>
          <% if timesheet.external_url.present? %>
            <small><span><i class="icon wb-link" aria-hidden="true"></i>URL Externa:</span> <%= link_to timesheet.external_url, "http://#{timesheet.external_url}", style: "color: #77838E;", target: "_blank" %></small><br>
          <% end %>
          <small><span><i class="icon wb-time" aria-hidden="true"></i>
            <% if timesheet.work_to.present? %>
            <%= timesheet.work_from %> até <%= timesheet.work_to %> (<%= timesheet.duration %> horas)
            <% else %>
              Em andamento
            <% end %>
          </small>
        </div>
        <div class="pl-0 pl-sm-20 mt-15 mt-sm-0 align-self-center">
          <%= link_to edit_timesheet_path(timesheet), class: "btn btn-outline btn-success btn-sm", method: :get do %>
            Editar</span>
          <% end %>

          <%= link_to timesheet, class: "btn btn-outline btn-danger btn-sm", method: :delete, data: { confirm: 'Tem certeza que deseja excluir este registro?' } do %>
            Excluir</span>
          <% end %>
        </div>
      </div><hr>
    </li>
  </ul>
  <nav>
    <ul data-plugin="paginator" data-total="50" data-skin="pagination-no-border"></ul>
  </nav>
</div>

app/views/timesheets/edit.html.erb
<div class="page">
  <div class="page-content">
    <div class="panel">
      <header class="panel-heading">
        <h3 class="panel-title">
          Editar Entrada
        </h3>
      </header>
      <div class="panel-body container-fluid">
        <div class="row row-lg">
          <div class="col-md-12 col-lg-9">
              <div class="example">
                <%= render "form" %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/timesheets/index.html.erb
<div class="page">

  <div class="page-header">
    <h1 class="page-title">Controle de horas</h1>
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="/">Início</a></li>
      <li class="breadcrumb-item active">Controle de horas</li>
    </ol>
    <div class="page-header-actions">
      <%= link_to new_timesheet_path, class: "btn btn-animate btn-animate-side btn-info btn-sm", method: :get do %>
        <i class="icon wb-plus" aria-hidden="true"></i>Entrada Manual
      <% end %>
    </div>
  </div>

  <div class="page-content">
    <div class="panel">
      <div class="panel-body">
          <% if @timesheets.present? %>
            <ul class="nav nav-tabs nav-tabs-line" role="tablist">
              <li class="nav-item" role="presentation"><a class="active nav-link" data-toggle="tab" href="#all_contacts"
                  aria-controls="all_contacts" role="tab">Últimas tarefas</a></li>
            </ul>
            <div class="tab-content">

              <%= render @timesheets.order("created_at desc") %>

              <%= paginate @timesheets %>
            </div>
            <% else %>
            <div class="tab-content">Você não possui horas cadastradas.</div>
            <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/timesheets/new.html.erb
<div class="page">
  <div class="page-content">
    <div class="panel">
      <header class="panel-heading">
        <h3 class="panel-title">
          Cadastrar Nova Entrada
        </h3>
      </header>
      <div class="panel-body container-fluid">
        <div class="row row-lg">
          <div class="col-md-12 col-lg-9">
              <div class="example">
                <%= render "form" %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>